import type { Metadata } from "next";
import { 
  Inter as FontSans,
  Libre_Baskerville as FontSerif,
} from "next/font/google";
import { cn } from "@/lib/utils";
import Header from "./_components/Header";
import "@/assets/styles/globals.css";

const fontSans = FontSans({
  subsets: ["latin"],
  variable: "--font-sans",
  display: 'swap',
})

const fontSerif = FontSerif({
  subsets: ["latin"],
  weight: ["400"],
  variable: "--font-serif",
  display: 'swap',
})


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html 
      suppressHydrationWarning={true}
      lang="en"
    >
      <head>
        <meta name="viewport" content="width=device-width, initial-scale=1.0" />
        <script 
          // This code is placed here because is needed to run before the app renders
          dangerouslySetInnerHTML={{
            __html: `
              const getSystemTheme = () => window.matchMedia("(prefers-color-scheme: dark)").matches ? 'dark' : 'light';
              const getStorageTheme = () => window.localStorage.getItem('data-theme');
              document.documentElement.classList.add(getStorageTheme() || getSystemTheme());
            `
          }}
        />
        <title>Amberpad</title>
      </head>
      <body 
        className={cn(
          'min-h-[100dvh]',
          'font-sans antialiased',
          'flex flex-col justify-start items-center',
          'overflow-x-hidden',
          fontSans.variable,
          fontSerif.variable,
        )}
      >
        <Header />
        {children}
      </body>
    </html>
  );
}
